services:
  - type: web
    name: n8n
    env: docker
    dockerImage: n8n-io/n8n:latest
    plan: starter
    healthCheckPath: /healthz
    envVars:
      - key: N8N_HOST
        fromService:
          type: web
          name: n8n
          property: host
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_DATABASE
        fromService:
          type: psql
          name: n8n-db
          property: database
      - key: DB_POSTGRESDB_HOST
        fromService:
          type: psql
          name: n8n-db
          property: host
      - key: DB_POSTGRESDB_PASSWORD
        fromService:
          type: psql
          name: n8n-db
          property: password
      - key: DB_POSTGRESDB_PORT
        fromService:
          type: psql
          name: n8n-db
          property: port
      - key: DB_POSTGRESDB_USER
        fromService:
          type: psql
          name: n8n-db
          property: user
      - key: GENERIC_TIMEZONE
        value: Europe/Moscow
      - key: WEBHOOK_URL
        value: https://${RENDER_EXTERNAL_URL}

  - type: psql
    name: n8n-db
    databaseName: n8n
    ipAllowList: []